apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o5qrcwt2q-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:a390290ab63f1cf6caa688eba5668537a94a1bd1@sha256:3e8e8f418b6811d5ed5de1abf8c96b5596084fea715996c4db1dd39d6d9ec7b6
          name: container-image
